//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoApp.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MemoApp.Localization.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major System Training.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range:.
        /// </summary>
        public static string Common_Range {
            get {
                return ResourceManager.GetString("Common_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string Common_To {
            get {
                return ResourceManager.GetString("Common_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major System Guide.
        /// </summary>
        public static string Help_Title {
            get {
                return ResourceManager.GetString("Help_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Training (00-09).
        /// </summary>
        public static string MainPage_BeginTraining {
            get {
                return ResourceManager.GetString("MainPage_BeginTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Range.
        /// </summary>
        public static string MainPage_CustomRange {
            get {
                return ResourceManager.GetString("MainPage_CustomRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End number.
        /// </summary>
        public static string MainPage_EndNumber {
            get {
                return ResourceManager.GetString("MainPage_EndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major System Guide.
        /// </summary>
        public static string MainPage_MajorSystemGuide {
            get {
                return ResourceManager.GetString("MainPage_MajorSystemGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Training.
        /// </summary>
        public static string MainPage_PresetTraining {
            get {
                return ResourceManager.GetString("MainPage_PresetTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Start.
        /// </summary>
        public static string MainPage_QuickStart {
            get {
                return ResourceManager.GetString("MainPage_QuickStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Custom Training.
        /// </summary>
        public static string MainPage_StartCustomTraining {
            get {
                return ResourceManager.GetString("MainPage_StartCustomTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start number.
        /// </summary>
        public static string MainPage_StartNumber {
            get {
                return ResourceManager.GetString("MainPage_StartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master the art of number memorization.
        /// </summary>
        public static string MainPage_Subtitle {
            get {
                return ResourceManager.GetString("MainPage_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major System Training.
        /// </summary>
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Numbers.
        /// </summary>
        public static string Statistics_AllNumbers {
            get {
                return ResourceManager.GetString("Statistics_AllNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers to Practice More.
        /// </summary>
        public static string Statistics_NumbersToPracticeMore {
            get {
                return ResourceManager.GetString("Statistics_NumbersToPracticeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Details.
        /// </summary>
        public static string Statistics_Title {
            get {
                return ResourceManager.GetString("Statistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        public static string TrainingOption_Beginner {
            get {
                return ResourceManager.GetString("TrainingOption_Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero-prefixed numbers (00-09).
        /// </summary>
        public static string TrainingOption_BeginnerDesc {
            get {
                return ResourceManager.GetString("TrainingOption_BeginnerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First 50.
        /// </summary>
        public static string TrainingOption_First50 {
            get {
                return ResourceManager.GetString("TrainingOption_First50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended practice (00-49).
        /// </summary>
        public static string TrainingOption_First50Desc {
            get {
                return ResourceManager.GetString("TrainingOption_First50Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Range.
        /// </summary>
        public static string TrainingOption_FullRange {
            get {
                return ResourceManager.GetString("TrainingOption_FullRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Major System (00-99).
        /// </summary>
        public static string TrainingOption_FullRangeDesc {
            get {
                return ResourceManager.GetString("TrainingOption_FullRangeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Digits.
        /// </summary>
        public static string TrainingOption_SingleDigits {
            get {
                return ResourceManager.GetString("TrainingOption_SingleDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic single digits (0-9).
        /// </summary>
        public static string TrainingOption_SingleDigitsDesc {
            get {
                return ResourceManager.GetString("TrainingOption_SingleDigitsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teens.
        /// </summary>
        public static string TrainingOption_Teens {
            get {
                return ResourceManager.GetString("TrainingOption_Teens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teen numbers (10-19).
        /// </summary>
        public static string TrainingOption_TeensDesc {
            get {
                return ResourceManager.GetString("TrainingOption_TeensDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenties.
        /// </summary>
        public static string TrainingOption_Twenties {
            get {
                return ResourceManager.GetString("TrainingOption_Twenties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty range (20-29).
        /// </summary>
        public static string TrainingOption_TwentiesDesc {
            get {
                return ResourceManager.GetString("TrainingOption_TwentiesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Time:.
        /// </summary>
        public static string TrainingSession_AverageTime {
            get {
                return ResourceManager.GetString("TrainingSession_AverageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        public static string TrainingSession_BackToHome {
            get {
                return ResourceManager.GetString("TrainingSession_BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Complete!.
        /// </summary>
        public static string TrainingSession_Complete {
            get {
                return ResourceManager.GetString("TrainingSession_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed: {0}.
        /// </summary>
        public static string TrainingSession_Completed {
            get {
                return ResourceManager.GetString("TrainingSession_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Number.
        /// </summary>
        public static string TrainingSession_CurrentNumber {
            get {
                return ResourceManager.GetString("TrainingSession_CurrentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your answer....
        /// </summary>
        public static string TrainingSession_EnterYourAnswer {
            get {
                return ResourceManager.GetString("TrainingSession_EnterYourAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest Time:.
        /// </summary>
        public static string TrainingSession_FastestTime {
            get {
                return ResourceManager.GetString("TrainingSession_FastestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Number.
        /// </summary>
        public static string TrainingSession_NextNumber {
            get {
                return ResourceManager.GetString("TrainingSession_NextNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string TrainingSession_Progress {
            get {
                return ResourceManager.GetString("TrainingSession_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining: {0}.
        /// </summary>
        public static string TrainingSession_Remaining {
            get {
                return ResourceManager.GetString("TrainingSession_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slowest Time:.
        /// </summary>
        public static string TrainingSession_SlowestTime {
            get {
                return ResourceManager.GetString("TrainingSession_SlowestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Statistics.
        /// </summary>
        public static string TrainingSession_Statistics {
            get {
                return ResourceManager.GetString("TrainingSession_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string TrainingSession_Submit {
            get {
                return ResourceManager.GetString("TrainingSession_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Session.
        /// </summary>
        public static string TrainingSession_Title {
            get {
                return ResourceManager.GetString("TrainingSession_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        public static string TrainingSession_Total {
            get {
                return ResourceManager.GetString("TrainingSession_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Duration:.
        /// </summary>
        public static string TrainingSession_TotalDuration {
            get {
                return ResourceManager.GetString("TrainingSession_TotalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string TrainingSession_ViewDetails {
            get {
                return ResourceManager.GetString("TrainingSession_ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Answer.
        /// </summary>
        public static string TrainingSession_YourAnswer {
            get {
                return ResourceManager.GetString("TrainingSession_YourAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start number must be less than or equal to end number..
        /// </summary>
        public static string Validation_RangeError {
            get {
                return ResourceManager.GetString("Validation_RangeError", resourceCulture);
            }
        }
    }
}